In [1]:
print("Hellow Numpy")

Hellow Numpy


# Array types and conversion between them

In [2]:
import numpy as np

integers = np.array([1,2,3,4,5,6])
print(integers)

[1 2 3 4 5 6]


In [5]:
# Accessing by index to integers array
# Numpy arrays are zero based
print("View by index:",integers[1])

# Assigned a new value to an specific index
integers[1] = 100
integers

View by index: 100


array([  1, 100,   3,   4,   5,   6])

In [6]:
# On numpy all data has to be all the same type
# for example we try to add a float number to integers array
integers[3] = 25.5
# The new value will be trucated to 25
integers

array([  1, 100,   3,  25,   5,   6])

In [15]:
# .dtype to know the type of array
print(integers.dtype)
# the value int64 refers to the number of allowed bytes

# for example:
print("Byte number for integers:", integers.nbytes)

# but if we create a low level array, for example
smallerInteger = np.array(integers, dtype=np.int8)
print(smallerInteger.dtype)

print("Byte number for int8:", smallerInteger.nbytes)

int64
Byte number for integers: 48
int8
Byte number for int8: 6


# Multidimencional arrays

In [25]:
# inside Numpy we can find differen dimentional arrays
"""
1D is a Vecto
2D is an array
3D o more is a tensor
"""

import numpy as np
# I've defined as 2D array 
numbers = np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(numbers)

# I can acces to a specific value by index
print("Row 0 - Colum 0, value:",numbers[0,0])

# I can know the number of dimentions of the numbers array using .ndim method
print("Number of dimentions:",numbers.ndim)

# I can create a 3D array
numbers_3D = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(numbers_3D)

# I can acces to a specific value by index
print("eje0 0 - eje1 1 - eje2 2, value:",numbers_3D[0,1,2])

# I can know the number of dimentions of the numbers array using .ndim method
print("Number of dimentions:",numbers_3D.ndim)

[[1 2 3 4 5]
 [6 7 8 9 0]]
Row 0 - Colum 0, value: 1
Number of dimentions: 2
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
eje0 0 - eje1 1 - eje2 2, value: 6
Number of dimentions: 3


# Creating arrays from List and other python structures

In [1]:
import numpy as np

In [3]:
# create an array from a list
list_1D = [1,2,3,4,5,6,7]
list_1D_array = np.array(list_1D)
print(list_1D_array)

[1 2 3 4 5 6 7]


In [4]:
# 2D array from python list
list_2D = [[1,2,3,4],[5,6,7,8]]
list_2D_array = np.array(list_2D)
print(list_2D_array)

[[1 2 3 4]
 [5 6 7 8]]


In [5]:
# Numpy will put the data type tha generalice all data store in python structure, for example
list_data = [1,2,'Hugo', 3, 'Andres']
gen_array = np.array(list_data)
print(gen_array)

['1' '2' 'Hugo' '3' 'Andres']


In [7]:
# Define an array from a tuple
tuple_1D = (1,2,3,4,5,6)
tuple_1D_array = np.array(tuple_1D)
print(tuple_1D_array)

[1 2 3 4 5 6]


In [8]:
# Define an array from a tuple
tuple_2D = ((1,2,3),(4,5,6))
tuple_2D_array = np.array(tuple_2D)
print(tuple_2D_array)

[[1 2 3]
 [4 5 6]]


In [11]:
# define an array from a dictionary, first we need to choose or the values o keys from the dictionary and after that
# we need to change tha type to listo usng list() method of python
dict_1D = {
    'name': 'Hugo',
    'age': 30
          }
dict_1D_array = np.array(list(dict_1D.values()))
print(dict_1D_array)

['Hugo' '30']


# Intrinsic Numpy array creation
Create an array manually can be tedius but we can use functions from Numpy to do that

In [13]:
# function arange(start, stop, step, like(data type), this function allow us to define a range of numbers as an array

array_arange = np.arange(10, 80, 5)
print(array_arange)

[10 15 20 25 30 35 40 45 50 55 60 65 70 75]


In [21]:
# fucntion linspace(start, stop, num(number of items))
# the numbers of items will be between the rang of start and stop
# specially usefull when I need an array of floating numbers
array_linspace = np.linspace(10, 50 , 10)
print(array_linspace)

# Also I can define the data type
array_linspace_2 = np.linspace(10, 50 , 10, dtype=str)
print(array_linspace_2)

[10.         14.44444444 18.88888889 23.33333333 27.77777778 32.22222222
 36.66666667 41.11111111 45.55555556 50.        ]
['10.0' '14.444444444444445' '18.88888888888889' '23.333333333333336'
 '27.77777777777778' '32.22222222222222' '36.66666666666667'
 '41.111111111111114' '45.55555555555556' '50.0']


In [27]:
# Using random function method from Numpy this one allows generate an array with random values
# .random.rand(4) -> will generate a 1D array with 4 floating random numbers

random_array_1 = np.random.rand(4)
print(random_array_1)

# also I can create a Ndimentional array using random.rand()
random_array_2 = np.random.rand(4, 4)
print(random_array_2)

[0.04330343 0.22990403 0.15912521 0.68540625]
[[0.26037141 0.93290893 0.73303803 0.6581537 ]
 [0.74030538 0.61380717 0.43552035 0.12111737]
 [0.03077793 0.35567994 0.36734167 0.48621474]
 [0.60667829 0.05442672 0.64034115 0.95496429]]


In [29]:
# In another hand random.randint(star, stop, num(number of items))
# this method will generate a integer array between start and stop taking the number of values required

random_array_2 = np.random.randint(10, 40, size=(6))
print(random_array_2)

# Also I can create a Ndimentional array with random.randint()
random_array_3 = np.random.randint(10, 40, size=(2,3))
print(random_array_3)

[13 14 14 15 30 19]
[[11 10 14]
 [26 26 25]]


# Creating arrays filled with constant values

In [32]:
# Using .zeros method of Numpy

zeros_array = np.zeros(5)
print(zeros_array)

zeros_array_2D = np.zeros((2,5))
print(zeros_array_2D)

[0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [35]:
# Using .ones method from Numpy

ones_array = np.ones(5)
print(ones_array)

# We can also define an arry fill of ones with 2D and a specific number of dimentions 
ones_array_2D = np.ones((3,2), dtype=int)
print(ones_array_2D)

[1. 1. 1. 1. 1.]
[[1 1]
 [1 1]
 [1 1]]


In [ ]:
# full and fill functions

# fill function is used to create one dimentional array
# -> Also fill function alluws me to fill and existing array with similar values

# full function is used to crate both 1D and 2D array



In [38]:
# The fill function works filled an existing empty array

first_fill_array = np.empty(8, dtype=int)
print(first_fill_array)

first_fill_array.fill(10)
print(first_fill_array)

[0 0 0 0 0 0 0 0]
[10 10 10 10 10 10 10 10]


In [39]:
# .full((row, colum), number)

first_full_array = np.full((3,3), 5)
print(first_full_array)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


# Findinf a shape and size of an array
An array has 4 main caracteristica
for example:
[
[1,2,3],
[1,2,3]
]

dtype: refers to data type, in this case integer
ndim: refers to number of dimentions
size: refers to number of elemento in the array
shape: refers to the number of dimentions of the array

In [44]:
# Shape

array = np.random.randint(10, 50, (3,3))
print(array)
print("Array shape: ", array.shape) # number of dimentions
print("Array size: ", array.size) # number of items

[[17 27 18]
 [46 37 39]
 [18 16 37]]
Array shape:  (3, 3)
Array size:  9


# Adding, removing and sorting elements

In [1]:
import numpy as np

array = np.array([1,2,3,4,5])
print(array)

[1 2 3 4 5]


In [2]:
# use of function .inser(array, index, data) -> this one insert the data in the specific index

new_array = np.insert(array, 3, [10,20])
print(new_array)

[ 1  2  3 10 20  4  5]


In [4]:
# use of function .append(array, data) -> this one add data to the endo of array

array_2 = np.array([6,7,8,9])
print(array_2)

new_array_2 = np.append(array_2, [20,30])
print(new_array_2)

[6 7 8 9]
[ 6  7  8  9 20 30]


In [5]:
# deleting data from an array .delete(array, index)

array_3 = np.array([10,20,30,40,50,60])
print(array_3)

new_array_3 = np.delete(array_3, 2)
print(new_array_3)

[10 20 30 40 50 60]
[10 20 40 50 60]


In [6]:
# sort function provides a copy of the given array but ordered

int_array = np.random.randint(10,50,10)
print(int_array)

sort_int_array = np.sort(int_array)
print(sort_int_array)

[11 16 44 29 15 45 37 27 16 12]
[11 12 15 16 16 27 29 37 44 45]


In [8]:
# SORT function also can order 2D arrays

int_array_2 = np.random.randint(0,10,[3,3])
print(int_array_2)

print(np.sort(int_array_2))

[[4 0 9]
 [4 4 7]
 [2 1 0]]
[[0 4 9]
 [4 4 7]
 [0 1 2]]


In [10]:
# Also SORT function can sort string content into an array

colors = np.array(['rojo', 'verde', 'azul', 'amarillo', 'morado'])
print(colors)

print(np.sort(colors))

['rojo' 'verde' 'azul' 'amarillo' 'morado']
['amarillo' 'azul' 'morado' 'rojo' 'verde']


# Copies and Views

In [15]:
# A view is a reference to the space memori where is located the original array

org_array = np.arange(5)
print("Original:",org_array)

view_array = org_array
print("View:",view_array)

# A view allows see a change in the original array from the copy or a change prom the copy in the original array
org_array[2] = 10
print("Original:",org_array)
print("View:",view_array)

# change made in the view but orginal can reflect the change as well
view_array[3] = 50
print("Original:",org_array)
print("View:",view_array)

Original: [0 1 2 3 4]
View: [0 1 2 3 4]
Original: [ 0  1 10  3  4]
View: [ 0  1 10  3  4]
Original: [ 0  1 10 50  4]
View: [ 0  1 10 50  4]
